import Head from 'next/head';
import Navbar from './Components/Navbar';

export default function Home() {
  return (
    <div >
      <Head>
        <title>Trevelicious</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
    </div>
  )
}
